name: Create Release
on:
  push:
    branches:
      - main
jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: main
      - name: Get version from package.json
        id: get-version
        run: |
          VERSION=$(cat package.json | jq -r '.version')
          echo "VERSION=$VERSION"
      # mainブランチに直接プッシュした場合はタグを作成しないようにするため、
      # releaseブランチからマージされたコミットがHEADになっているかを確認
      - name: Check if release branch is merged into main
        env:
          VERSION: ${{ steps.get-version.outputs.VERSION }}
        run: |
          if git rev-parse HEAD != $(git rev-parse origin/release/$VERSION); then
            echo "Release branch is not merged into main"
            exit 1
          fi
      - name: Check if tag already exists
        env:
          VERSION: ${{ steps.get-version.outputs.VERSION }}
        run: |
          if git ls-remote --tags origin v$VERSION | grep -q .; then
            echo "Tag v$VERSION already exists"
            exit 1
          fi
      - name: Create release tag
        env:
          VERSION: ${{ steps.get-version.outputs.VERSION }}
        run: |
          git pull origin main
          git tag -a v$VERSION -m "Release v$VERSION"
          git push origin v$VERSION
  create-build-artifacts:
    runs-on: ubuntu-latest
    needs: [create-release-tag]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: main
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Create zip file
        env:
          VERSION: ${{ steps.get-version.outputs.VERSION }}
        # zipを解凍したらルートにdistの中身が入るようにするため、distディレクトリの中にある全ファイルをzipに圧縮
        run: |
          zip -r super-mouse-gesture-$VERSION.zip dist/*
      - name: Upload zip file
        env:
          VERSION: ${{ steps.get-version.outputs.VERSION }}
        uses: actions/upload-artifact@v6
        with:
          name: super-mouse-gesture-$VERSION.zip
          path: super-mouse-gesture-$VERSION.zip
  create-release:
    runs-on: ubuntu-latest
    needs: [create-build-artifacts]
    steps:
      - name: Download zip file
        env:
          VERSION: ${{ steps.get-version.outputs.VERSION }}
        uses: actions/download-artifact@v6
        with:
          name: super-mouse-gesture-$VERSION.zip
          path: super-mouse-gesture-$VERSION.zip
      - name: Create release
        # リリースノートをリリースページで記載してから公開するため、draftで作成
        env:
          VERSION: ${{ steps.get-version.outputs.VERSION }}
        run: |
          gh release create v$VERSION --title "v$VERSION" --notes "Release v$VERSION" --generate-notes --draft
          gh release upload v$VERSION super-mouse-gesture-$VERSION.zip
